
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/ide-desktop/clion/backend/bin/cmake/linux/x64/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:10 (project)"
    message: |
      The system is: Linux - 6.1.27-060127-generic - x86_64
...
